knuckleswtf/scribe

- composer.json
- src/Writing/PostmanCollectionWriter.php
- tests/Fixtures/TestController.php
- tests/Fixtures/collection.json
- tests/Fixtures/collection_custom_url.json
- tests/Fixtures/collection_with_body_parameters.json
- tests/Fixtures/collection_with_form_data_parameters.json
- tests/Fixtures/collection_with_query_parameters.json
- tests/Fixtures/collection_with_secure_url.json
- tests/GenerateDocumentationTest.php
This will generate proper json for  postman if request is form-data otherwise will default to raw json
> form-data support

- docs/documenting/documenting-endpoint-responses.md
Substitute `responses` with `with` in Loading spefic relations example
> **Please read the [contribution guidelines](https://scribe.readthedocs.io/en/latest/contributing.html), especially the section on making a pull request, before creating a PR.** Otherwise, your PR may be turned down.
> Documenting endpoint update

- src/Writing/PostmanCollectionWriter.php
- tests/Fixtures/collection.json
- tests/Fixtures/collection_custom_url.json
- tests/Fixtures/collection_with_body_parameters.json
- tests/Fixtures/collection_with_custom_headers.json
- tests/Fixtures/collection_with_form_data_parameters.json
- tests/Fixtures/collection_with_query_parameters.json
- tests/Fixtures/collection_with_secure_url.json
Fixes import to Insomnia
Fixes #40 
> **Please read the [contribution guidelines](https://scribe.readthedocs.io/en/latest/contributing.html), especially the section on making a pull request, before creating a PR.** Otherwise, your PR may be turned down.
> Resolves #40 - Include raw in requests.url

- docs/customization.md
> Add views publication doc support for Lumen

- docs/guide-getting-started.md
> docs: fix documenting api urls

- .travis.yml
- README.md
- composer.dingo.json
- composer.json
- config/scribe.php
- docs/architecture.md
- docs/config.md
- docs/documenting/documenting-api-information.md
- docs/generating-documentation.md
- docs/guide-getting-started.md
- docs/index.md
- phpunit.xml
- resources/views/partials/frontmatter.blade.php
- routes/laravel.php
- src/Http/Controller.php
- src/Writing/OpenAPISpecWriter.php
- src/Writing/Writer.php
- tests/Fixtures/openapi.yaml
- tests/GenerateDocumentationTest.php
- tests/Unit/OpenAPISpecWriterTest.php
> Added OpenAPI spec generation support

- docs/documenting/documenting-endpoint-responses.md
- src/Extracting/Strategies/Responses/UseTransformerTags.php
Added Fractal resourceKey support for Fractal Items
> Adds resourceKey support for fractal transformers

- src/Http/Controller.php
> Fix openapi route

- src/Extracting/DatabaseTransactionHelpers.php
> Fixed throwing exception during fetching connection driver for DB transactions.

- .travis.yml
- README.md
- composer.dingo.json
- composer.json
- docs/index.md
- phpunit.xml
- src/Commands/GenerateDocumentation.php
- src/Extracting/Strategies/BodyParameters/GetFromBodyParamTag.php
- src/Extracting/Strategies/BodyParameters/GetFromFormRequest.php
- src/Extracting/Strategies/Headers/GetFromHeaderTag.php
- src/Extracting/Strategies/QueryParameters/GetFromQueryParamTag.php
- src/Extracting/Strategies/UrlParameters/GetFromUrlParamTag.php
- src/Matching/MatchedRoute.php
- src/Matching/RouteMatcher.php
- src/Matching/RouteMatcherInterface.php
- tests/Unit/PostmanCollectionWriterTest.php
- Renamed `Match` class to `MatchedRoute`
- Added type guard for union types when fetching parameter class names
> PHP 8 compatibility

- src/Writing/PostmanCollectionWriter.php
- tests/Fixtures/collection.json
This is a quick PR to add responses to Postman Collections as mentioned here: #177
> Add responses to Postman Collection

- docs/migrating-v2.md
Sorry for two different PRs for docs typo fixes.
> Fix docs typo

- src/Extracting/Strategies/UrlParameters/GetFromLaravelAPI.php
Hi, I fixed #262.
If route key is customized, change key's type to string.
> Support customizing the route key.

- src/Extracting/Strategies/GetFromInlineValidatorBase.php
I also encountered this [bug](https://github.com/knuckleswtf/scribe/issues/279), and this solves the issue.
> fix https://github.com/knuckleswtf/scribe/issues/279

- .gitattributes
- CHANGELOG.md
- camel/BaseDTO.php
- camel/BaseDTOCollection.php
- camel/Extraction/ExtractedEndpointData.php
- camel/Extraction/ResponseCollection.php
- composer.dingo.json
- composer.json
- src/Tools/Globals.php
- tests/Strategies/Responses/ResponseCallsTest.php
- tests/Unit/PostmanCollectionWriterTest.php
> Support for spatie/data-transfer-object 3

- src/Tools/Utils.php
Fixes a problem caused by a backslash escaping the next character in a string.
The bug prevented the exception on line 204 to be thrown.
> Fix factory error detection

- src/Extracting/ParsesValidationRules.php
- tests/Unit/ValidationRuleParsingTest.php
> generating long number fix

- src/Matching/LumenRouteAdapter.php
> small_fix: lumen-route-docblock

- resources/js/theme-default.js
Tried to fix the issues with the headers. Give this a shot now. The changes look at the nav to figure out how to track the titles. I also tweaked the ratio of the viewport. Might need some more tweaks but the logic is slightly better now
> Fixed: reduce margins and only pay attention to menu anchors

- camel/Extraction/ExtractedEndpointData.php
Hello,
I'm using laravel api resources and I solved my documentation generation issues with this PR.
I haven't tested in other cases at the moment.
Regards
> Resolve issue with api resource

- src/Extracting/Strategies/Responses/UseApiResourceTags.php
> fix[ISSUE-321]: added `load` for relations in factory->create

- resources/css/theme-default.style.css
> Remove unnecessary bracket in theme-default.style.css

- src/Tools/Utils.php
docblock should be read from the asController method
fix #604
> Add support for the Laravel Actions package

- src/Extracting/Strategies/GetFromInlineValidatorBase.php
- tests/Fixtures/TestController.php
- tests/Strategies/GetFromInlineValidatorTest.php
Adds support to parse inline Enum Rule class.
> Parses inline Enum Rules

- src/Commands/Upgrade.php
> Upgrader: Ignore examples.models_source

- src/Commands/GenerateDocumentation.php
Ignore examples.models_source like in #631
> Add missing dontTouch to scribe:generate

- resources/js/theme-default.js
As requested, here is a script that will open menu items as you scroll through the page.
Closes #422
> Menu items now open when you scroll down in the default theme.

- src/Writing/PostmanCollectionWriter.php
When query param empty I want to show Postman
> Also show empty array query parameters in Postman

- camel/Output/OutputEndpointData.php
- resources/js/tryitout.js
Hi,
sorry my last fix (https://github.com/knuckleswtf/scribe/pull/697) wasn't really effective here's another that should handle the dot in all JS function calls
> Replace dot in endpointId

- config/scribe.php
> remove double backtick on scribe.php

- resources/views/components/nested-fields.blade.php
Added missing field. Solves https://github.com/knuckleswtf/scribe/issues/758
> Fix: Enum values not getting written to HTML

- composer.dingo.json
- composer.json
- composer.lowest.json
> chore: allow nikic/php-parse v5

- CONTRIBUTING.md
Just saving a couple of clicks here.
~~https://scribe.rtfd.io/en/latest/contributing.html~~  >  https://scribe.knuckles.wtf/laravel/contributing
> Update contribution guide link

- composer.json
> Upgraded "shalvah/upgrader" to "0.4.0"

- resources/views/external/elements.blade.php
> Fix typo on elements.blade.php

- config/scribe.php
[Link](https://www.scribbr.com/definitions/for-example-abbreviation/)
> Some Grammar Corrections
