knuckleswtf/scribe

src/Extracting/DatabaseTransactionHelpers.php, src/Extracting/Strategies/Responses/ResponseCalls.php, src/Extracting/Strategies/Responses/UseApiResourceTags.php, src/Extracting/Strategies/Responses/UseTransformerTags.php, tests/Fixtures/TestModel.php
Closes #4 
For ApiResource and Transformer strategies the model types connection is used to start the transaction. For the ResponseCall strategy a transaction for every database connection is started since we don't know which one is used for a specific route.
=> Added support for multiple database connections

config/scribe.php
As per #22 - updated base configuration file
=> Resolves #22 - Set the correct config key for documentation URL

docs/contributing.md
This is a slight grammar fix in the contributing guidelines.
=> change 'describe' to 'description' and improve contributing doc

config/scribe.php, src/Writing/Writer.php, tests/GenerateDocumentationTest.php
In the [document](https://github.com/knuckleswtf/scribe/blob/6863189588e4a9a1269c5c9b41de6a9905d80131/docs/generating-documentation.md#L26) mentioned that a `postman.base_url` can be specified for postman collection generated.
However after reviewing the code, I find only the `base_url` in the outer array can be changed and by changing it will change both the postman collection's `base_url` and the examples.
Since I think many users might preferred having different customization of page and postman, I've tried to implement this feature.
=> feat(config): ability to set postman base_url independently

src/Extracting/Generator.php, src/Tools/ConsoleOutputUtils.php, tests/GenerateDocumentationTest.php
> **Please read the [contribution guidelines](https://scribe.readthedocs.io/en/latest/contributing.html), especially the section on making a pull request, before creating a PR.** Otherwise, your PR may be turned down.
When a route that uses the `HEAD` verb exclusively is encountered, the `Writer` causes an `Undefined Offset` exception to be thrown as `HEAD` verbs are filtered out of the list of methods for an endpoint.
This solution makes an exception for `HEAD` where it is the **only** method specified by the developer. This is so that the original functionality is retained.
As per my comments on #53, I think that filtering out `HEAD` obfuscates what is actually happening; and Laravel should probably provide guidance/configurability for what appears to be a widely undesired behaviour; …
=> [#53] Fixed issue where purposeful head requests aren't rendered

config/scribe.php, src/Exceptions/DbTransactionSupportException.php, src/Exceptions/ScribeException.php, src/Extracting/DatabaseTransactionHelpers.php, src/Extracting/Strategies/Strategy.php
Some third-party database drivers don't support transactions *cough* Jenssegers *cough*. I'm sure there are probably some more out there.
Thought I'd throw this out there as a possible solution, and get guidance from maintainers before writing the relevant Unit tests. 
Potentially fixes #48 
> **Please read the [contribution guidelines](https://scribe.readthedocs.io/en/latest/contributing.html), especially the section on making a pull request, before creating a PR.** Otherwise, your PR may be turned down.
=> [WIP] [#48] Added defensive code for DatabaseConnection drivers that don't support transactions

config/scribe.php, docs/config.md, docs/generating-documentation.md, src/Writing/PostmanCollectionWriter.php, src/Writing/Writer.php, tests/Fixtures/collection-overridden.json, tests/Fixtures/openapi-overridden.yaml, tests/GenerateDocumentationTest.php, tests/Unit/PostmanCollectionWriterTest.php
To override specfic fields, use the `postman.overrides` and `openapi.overrides` keys. Dot notation is supported. For instance, to override the version and base URL for the OpenAPI spec, you can do:
```php
'openapi' => [
'overrides' => [
'info.version' =>'2.0',
'servers.0.url' = 'https://api.dev',
]
]
```
=> Added support for overriding parts of the generated Postman collection or OpenAPI spec

src/Writing/OpenAPISpecWriter.php, src/Writing/Writer.php
Had some things broken due to no checks for empty values in 1.4. No changes to my config generated with 1.3 (using the default config with the exception of a custom Serializer).
<code>
🔊 info Generating Postman collection
ErrorException 
count(): Parameter must be an array or an object that implements Countable
at vendor/knuckleswtf/scribe/src/Writing/Writer.php:223
219|         );
220| 
221|         $collection = $writer->generatePostmanCollection();
222|         $overrides = $this->config->get('postman.overrides');
> 223|         if (count($overrides)) {
224|             foreach ($overrides as $key => $value) {
225|                 data_set($collection, $key, $value);
226|             }
227|         }
+18 vendor frames 
19  artisan:37 …
=> Breaking changes due to Overrides update

src/Extracting/DatabaseTransactionHelpers.php
I ran into problems where generating documentation would result in data being added to my database.
After investigating I found that a DatabaseTransaction is only started for the first connection in the config.
[This comment](https://github.com/knuckleswtf/scribe/pull/5#pullrequestreview-407382542) on a previous PR makes me believe the intention is to start a transaction for all available connections. 
This PR should fix that
=> Properly iterate over all database transactions

config/scribe.php, docs/config.md, docs/documenting/documenting-api-information.md, src/Extracting/Generator.php
This is about turning `"Authorization: Bearer ba5cdZPkVhaD4feg3v686E1"` into `"Authorization: Bearer {ACCESS_TOKEN}"`  in code examples, simply by setting the config option `auth.display_value` to `"{ACCESS_TOKEN}"`.  It would also replace random token value in code examples for other `auth.in` option values, not only `bearer`.
I also wrote short explanation in the docs, if you think something is missing, let me know. I'm open for suggestions.
P.S. I found no tests for `auth.display_value` config option, so I have no idea what and how should I test for. I would appreciate some help in that area.
=> Add ability to replace random token string in generated code examples

src/Extracting/Strategies/Responses/UseApiResourceTags.php, src/Extracting/Strategies/Responses/UseTransformerTags.php, tests/Fixtures/TestUser.php, tests/Fixtures/TestUserApiResource.php, tests/Fixtures/TestUserApiResourceCollection.php, tests/Strategies/Responses/UseApiResourceTagsTest.php
✅ This is a fix proposal for the bugs related to the issues:
* [Models created by factory are deleted before calling the resource](https://github.com/knuckleswtf/scribe/issues/56)
* [Load relations not working](https://github.com/knuckleswtf/scribe/issues/46)
🛠️ Major changes
* Database transactions moved into `getApiResourceResponse` to avoid relation deletion before a lazy load.
* Added the route resolver
=> Issues 56 and 46 fix proposal

src/Writing/PostmanCollectionWriter.php
The protocol cloud not be correctly resolved and would always default to http. This because $baseUrl would always contain the url witouth http or htpps prefix. Because of this the function `Str::startsWith($baseUrl, 'https') ? 'https' : 'http'` will always return http.
```php
$baseUrl = $this->getBaseUrl($this->config->get('postman.base_url', $this->config->get('base_url')));
$base = [
'protocol' => Str::startsWith($baseUrl, 'https') ? 'https' : 'http',
];
```
Change the code as bellow. This will resolve the correct prefix for the url (eithet http or https)
```php
$protocol = Str::startsWith($this->config->get('postman.base_url', $this->config->get('base_url')), 'https') ? 'https' : 'http';
$baseUrl = $this->getBaseUrl($this->config->get('postman.base_url', …
```
=> Set correct base URL protocol for Postman collection

src/Http/Controller.php
Hello All,
I had an issue opening the URL for OpenApi specification, it responds with `500 Internal Server Error` with exception message `The file "scribe/openapi.yaml" does not exist` if the default disk is not `local`.
After investigating I have found that the disk does not explicitly defined for `scribe/openapi.yaml` file.
This PR specifies the `local` disk for responding with `scribe/openapi.yaml` file as it happens for `scribe/collection.json` file.
=> Explicitly specify the disk for openapi.yaml file

src/Tools/Utils.php
Related issue: https://github.com/knuckleswtf/scribe/issues/169
As mentioned on the issue, using package with legacy factories will break the usage of factories when generate de doc.
This PR changes the ability to check if use laravel 8 factories.
=> Check first laravel 8 factory

resources/views/components/field-details.blade.php
If the param name contains 'password' hide the input text by setting `type="password"` for `input`.
Before:
After:
=> If param name contains password set input type to password

src/Writing/PostmanCollectionWriter.php
This PR will format the form params properly in Postman.
Currently an object would be formatted eg. patient = [Object object] in Postman
This PR corrects that by formatting it as patient[key] = value instead
=> format form data params properly

src/Writing/PostmanCollectionWriter.php
In some locales like **zh-tw**, `json_encode()` will make the content to `\u....`
I want to add the flag `JSON_UNESCAPE_UNICODE` could show the correct words, and will not affect other locales
Thanks.
=> unescape unicode when generate postman collections for other locale

src/Writing/Writer.php
Hello, 
I've notticed that using this package, you cannot overwrite name of public directory.  Most of apps that I am developing has changed public directory to public_html. 
Overwritting is possible and described in this issue: [https://github.com/laravel/framework/issues/18550](https://github.com/laravel/framework/issues/18550)
When you configure scribe to return laravel views the name "public" is provided from string, not from laravel helper function.
I made change to use laravel helper function, and test it manually. Then I've ran composer test and everything seems working well. 
Please let me know if this change is good enough.
Regards,
=> Use of public directory by laravel app helper function

src/Writing/Writer.php
Hello @shalvah 
I found I misspelled path.public argument of app()->get() method. In #214. 
You cannot generate documentation with laravel type becouse of this bug 
It is is fixed now
Sorry for complicating.
Regard,
=> Repaired misspelled path.public argument of app()->get() method

src/Writing/Writer.php
Hello again,
I found error when I generated documentation many times. This occurs on laravel type, when you public/vendor/scribe is not empty.
I fixed it.
Regards,
=> Fixed error public/vendor/scribe is not empty

src/Extracting/Strategies/BodyParameters/GetFromFormRequest.php
Hi @shalvah !
I don't know if this is acceptable but I found a solution to my problem and I think it can help some of us :)
In case FormRequest class needs dependency injection, instanciation throws an ArgumentCountError exception.
By catching it, we can simply skip this class and the developer can use `@bodyParam` annotation to add documentation on the params.
See https://github.com/knuckleswtf/scribe/issues/189
=> Skip FormRequest if instanciation isn't possible

docs/customization.md
Missing letter aside, it should use rst syntax for linking, not markdown as it's inside an `eval_rst`.
=> Fix link inside rst area (docs)

.gitattributes
I think its safe to ignore the `docs` folder on `.gitattributes` file as it happends to save some space when installing scribe.
It will save approximately `1.4 MB` of disk space
Note: I also found that `pastel` also ignore the docs folder, see https://github.com/knuckleswtf/pastel/blob/476e86cd237c7256b5365efd844084a49075543a/.gitattributes#L1-L4
=> update .gitattributes to ignore docs

src/Writing/Writer.php
In scribe configfile there is `interactive` options to toggle tryitout feature.
Currently when we toggle `interactive` to `false`, the `tryitout.js` file still copied into static folder.
This PR makes the copy file respect the interactive configuration.
=> Respect interactive config for tryitoutjs

src/Extracting/Strategies/Responses/UseApiResourceTags.php
This comment:
```
* @apiResource 201 \App\Http\Resources\Advertisers\UserManagement\StaffResource
```
Throw error:
```
Spatie\DataTransferObject\DataTransferObjectError 
Invalid type: expected `Knuckles\Camel\Extraction\Response::status` to be of type `integer`, instead got value `201`, which is string..
```
So, to fix the added cast to integer status
=> Update UseApiResourceTags (fix invalid type error)

src/Extracting/Generator.php, tests/Unit/GeneratorTest.php
Fixed a bug where a request body that is an array of objects was not included in the documentation. For example: 
```
* @bodyParam [].row_id string A unique ID. Example: 700
* @bodyParam [].name string required An element name. Example: My item name
* @bodyParam [].description string An optional description of the element.
```
This was being properly parsed by the `GetFromBodyParamTag.php` strategy, but the body content was missing from the documentation and the code samples. Now, in this example, this will be added to the documentation:
And this. will be added to the code sample (JS example):
```
let body = [
{
"row_id": "700",
"name": "My item name"
}
]
```
=> Fixed an issue processing body parameters when the request body itself is an array.

config/scribe.php
I found the url in comment for `example_languages` in `config.php` is wrong, so I just modify it to the right one.
The url should be `https://scribe.knuckles.wtf/laravel/advanced/example-requests`  in `example_languages` section.
=> Update the doc url with in config.php

resources/views/themes/default/endpoint.blade.php
Hi, thank you for such a fantastic library.
I encountered #240 issue.
`tryitout-3.0.2.js` is checking hasFiles attribute is "0".
```javascript
if (form.dataset.hasfiles === "0") {
body = {};
setter = (name, value) => _.set(body, name, value);
} else {
body = new FormData();
setter = (name, value) => body.append(name, value);
}
```
But generated html has not "0" or "1"
```html
<form id="form-POSTapi-v1-login" data-method="POST" data-path="api/v1/login" data-authed="0" data-hasfiles="" data-headers="{&quot;Content-Type&quot;:&quot;application\/json&quot;,&quot;Accept&quot;:&quot;application\/json&quot;}" onsubmit="event.preventDefault(); executeTryOut('POSTapi-v1-login', this);">
```
=> Fix body params format

src/ScribeServiceProvider.php
Fixes #253 
Registering `blademd` in the register method of the service provider causes problems because it uses other service providers that may not have been registered yet. This moves that code to the boot method instead.
https://laravel.com/docs/8.x/providers#the-register-method
https://laravel.com/docs/8.x/providers#the-boot-method
=> Move blademd registration to boot method of service provider

resources/js/tryitout.js
Hi! I fixed #232.
When I sent FormData without setting the Content-type, the Content-type was automatically set with boundary.
But I'm not sure it's best way to fix. So If you don't like it, feel free to ignore it.
=> Fix the boundary is missing in the headers.

src/Commands/GenerateDocumentation.php, src/GroupedEndpoints/GroupedEndpointsContract.php, src/GroupedEndpoints/GroupedEndpointsFactory.php, src/GroupedEndpoints/GroupedEndpointsFromApp.php, src/GroupedEndpoints/GroupedEndpointsFromCamelDir.php
Separate the concern of getting groupedEndpoints by creating different strategies for getting groupedEndpoints. 
Before, the command class `GenerateDocumentation` contains all the helper methods in getting the groupedEndpoints.
In this PR, I refactor it by creating different strategies in getting the groupedEndpoints. 
When I read the code, currently there are two ways of getting the groupedEndpoints:
1. First is extracting the endpoints from the Laravel app, I call this strategy class `GroupedEndpointsFromApp`
2. Then the other one is getting it from the generated YAML from the camelDir, I call this `GroupedEndpointsFromCamelDir`. 
So first there is `GroupedEndpointsFactory` that will return the appropriate strategy, either `GroupedEndpointsFromApp` if it `isForcing` or `shouldExtract` …
=> Separate the concern of getting groupedEndpoints by creating different strategies

src/Extracting/RouteDocBlocker.php
This PR adds a method `getDocBlocks(Route $route, $className, $methodName = null)` in `RouteDocBlocker`. 
The reason behind this so that we can pass a different `className` and `methodName`. In my plugin, [scribe-tdd](https://github.com/ajcastro/scribe-tdd), The docblocks annotations are used in the test classes and methods. 
Therefore, I plan to create a strategy with implementation to use this like so: 
```php
RouteDocBlocker::getDocBlocks($route, 'Tests\Features\Http\UserControllerTest', 'test_users_index');
```
This will parse the docblocks in the test class and its method.
You can check a fork of the `TheSideProjectAPI` where I move the docblock annotations to the test classes:
https://github.com/ajcastro/TheSideProjectAPI/pull/1
=> Add getDocBlocks() in RouteDocBlocker

src/Extracting/ParamHelpers.php
This PR fixes the scenario when the value is null and the type is array.
I encountered this error but can't find which specific data that caused that. The value is null that's why it errors.
=> Fix condition when value is null and type is array

src/Extracting/Strategies/GetFromInlineValidatorBase.php
I encountered another variant of this bug, where the "parts" might not always be defined, causing a fatal error. This solution fixes it.
=> Fix https://github.com/knuckleswtf/scribe/pull/281 (again)

src/Tools/WritingUtils.php
Currently, `boolean` types in query params are either `"1"` or `""`, the later case should be `"0"`, this PR fixes that
=> Format booleans as "1"/"0" in query params

resources/js/tryitout.js
Radio buttons would call `_.set` for each of them, meaning that the value of the parameter would always be the set to the same as the last added. (`false` in the case of `boolean` validations)
With this change, the selected value is set instead.
=> Group radio buttons when setting query parameters

config/scribe.php, resources/js/tryitout.js, resources/views/themes/default/index.blade.php
These additions allow supporting CSRF tokens for apps using Laravel Sanctum. You can provide a URL that gives you the token, which it then applies, to each URL being called.
This should address #243.
There are probably some docs updates here just to call this feature out, but I can do these when/if this is accepted.
=> Added: support for csrf tokens that apply automatically

config/scribe.php
This is annoying but I screwed up the sanctum URL. It was `csrf-cookie` not `csrf-token`.
I was testing 3.10 when I found this error
=> Fixed: bad csrf URL for sanctum

src/Tools/Utils.php, tests/Fixtures/TestPet.php, tests/Fixtures/TestPetApiResource.php, tests/Fixtures/TestPetApiResourceCollection.php, tests/Fixtures/TestUser.php, tests/Fixtures/TestUserApiResource.php, tests/Strategies/Responses/UseApiResourceTagsTest.php
Allows for factoring nested relations with dot notation. Supports `HasMany` and `BelongsToMany` relations type. In case of custom data in pivot table you should create helper function in your factory which must be names as `pivot{name of relationship method}`. 
`employees` <-- one to many --> `places` <-- many to many --> `tasks`.
Each `employee` has assigned many `places` of work and each `places` belongs to many `tasks`. Pivot table between `places` and `tasks` has additional column with `salary`. Resource returns those relations with information about salary from pivot.
```php
class Employee extends Model
{
use HasFactory;
public function places(): HasMany
{
return $this->hasMany(Place::class);
}
}
```
```php
class Place extends Model
{
use HasFactory;
public function tasks(): …
```
=> Feat nested relations

resources/js/theme-default.js, resources/views/themes/default/index.blade.php, resources/views/themes/default/sidebar.blade.php
This allows you to define custom language names which will be used in the output docs language switcher buttons, e.g.:
```php
'example_languages' => [
'bash',
'javascript',
'TS' => 'typescript',
],
```
Also fixes the language switcher on mobile which was broken (wouldn't switch language and would always send you to the top of the page).
=> Add ability to define custom names for languages in config, by using the array key

camel/Extraction/Metadata.php, tests/Fixtures/TestCustomEndpointMetadata.php, tests/Unit/ExtractorTest.php
Resolves https://github.com/knuckleswtf/scribe/issues/380
I'll make a separate PR for the docs
=> Add support for custom endpoint metadata definitions

src/Writing/HtmlWriter.php
i created a custom theme
but there was an error when running the command php artisan scribe:generate
error while copying css and js files to custom theme: "copy(public/docs/js/tryitout-3.16.0.js): failed to open stream: No such file or directory"
=> Fixed: error when copying custom theme assets files

config/scribe.php, src/Writing/PostmanCollectionWriter.php, tests/Fixtures/collection.json, tests/Unit/PostmanCollectionWriterTest.php
For now `baseUrl` not include protocol, only `localhost` or `example.com`, and in postman will be like this : 
```
http://{{baseUrl}}/some/other
```
It makes difficult when we want to change baseUrl from `http` to `https`, for example in local we use `http://localhost` but in staging we use `https://staging.example.com`. So, we must change environment variable in postman, then change `http` to `https` manually.
We can't only change environment variable, because `baseUrl` not contains protocol (http or https). It will be helpful when we can set `baseUrl` is http://localhost (including protocol).
So, I'm change baseUrl contain protocol, and also remove `protocol` attribute on `url` json.
```json
"variable": [
{
"id": "baseUrl",
"key": "baseUrl",
"type": "string",
"name": "string",
"value": …
```
=> Feat: base url contain protocol

src/Extracting/ParsesValidationRules.php
Showing all fields in description of required_if fields instead of just one.
=> Fix handling multiple fields for required_if

src/Extracting/Strategies/UrlParameters/GetFromLaravelAPI.php
Hello,
This PR allows you to search for an existing ID in DB rather than using when no example.
Regards
=> ADDED - search id in DB when model instance

src/Tools/ErrorHandlingUtils.php
Type: Bug
Tested on: PHP 7.4, Laravel 6.18.1
Instance of Symfony\Component\Debug\Exception\FatalThrowableError cannot be caught as Exception, use Throwable instead.
=> Fix ErrorHandlingUtils for Laravel 6

src/Tools/Utils.php
When using bigger (more than two relations) chains (like event.tag.tagGroup), exploding by dot will be broken: 
It will cast as `event.tag` and `event.tagGroup` not as `event.tag.tagGroup`.
=> fix(model factory chain): implode relation chains for bigger relations

src/Extracting/ParsesValidationRules.php, tests/Unit/ValidationRuleParsingTest.php
When using `accepted` or `accepted_if` validation rules on a field, the generated body parameters documentation hints that the value is an optional string. This is not true, as you can see in the Laravel Validation documentation: [https://laravel.com/docs/9.x/validation#rule-accepted](https://laravel.com/docs/9.x/validation#rule-accepted)
This PR aims to change the type, description and requirement of fields with those rules.
Documentation and example request generated before the changes:
Documentation and example request generated after the changes:
=> Fix validation rule accepted

config/scribe.php, src/Writing/Writer.php
Hi! I needed this functionality for a project, and after some thought I concluded that the best way to implement it would be to actually add the functionality directly to Scribe.
This allows you to customize the location of the public assets generated for laravel blade documents. By default, the assets are created in `public/vendor/scribe`. With this feature, if the user defines a `laravel.asset_prefix` value, the path becomes `public/{{ asset_prefix }}/vendor/scribe`. 
I'm unclear how to best test this (my code currently passes all tests) so I'd be curious for ideas. Open to feedback.
=> add assets prefix functionality

src/Writing/PostmanCollectionWriter.php
This PR. fixes the multipart/form-data with PUT & PATCH requests.
Also allowed to change body mode to `urlencoded`
fixes https://github.com/knuckleswtf/scribe/issues/421
=> Change PUT & PATCH requests to POST with _method parameter if the request is multipart/from-data

resources/views/themes/default/sidebar.blade.php
This PR fixes [#436](https://github.com/knuckleswtf/scribe/issues/436) Logo image is partly covered by scrollbar
=> Logo image is partly covered by scrollbar 

resources/js/theme-default.js
Because the style have padding top and bottom for `pre` tag, it will be better on switching the example code, we hide the `pre` tag instead `code` tag. 
With `code` tag, it create a big gap between `example request` title and the code
This is before fix
This is after fix
=> hide pre tag instead code tag on switching the language

resources/js/tryitout.js
This PR fixes #490 
- #490 
I couldn't find E2E test of the JS client on the generated documentation so I tested the option parameter on the generated documentation with an empty value to make sure no query parameter was appended to the actual request being sent.
If you want E2E testing with Jest or others, including JS clients, please let me know. I don't know if it should be included in this PR or not.
If I put value on optional parameter, then query parameter appended.
If I put empty value, then query parameter will be not appended.
=> fix: 🐛 empty query parameter sent even if input is empty

camel/Extraction/ExtractedEndpointData.php, tests/Fixtures/TestPost.php, tests/Fixtures/TestPostController.php, tests/Fixtures/TestPostUserController.php, tests/GenerateDocumentationTest.php
This pull request fixes #275. The bug is that Scribe uses the `id` as the default URL parameter when no inline binding is applied, but the user might be using another column by overriding the `getRouteKeyName()` method in the model.
1. If there is an inline binding in the route, use it.
2. Else, if it is a resource route parameter, use the `id`.
3. Otherwise, keep the same parameter name.
1. If there is an inline binding in the route, use it.
2. Else, If there is a type-hinted variable in the controller action, with the same name as the route segment name, use it to call `getRouteKeyName()`.
3. Else, if it is a resource route parameter, use the `id`.
4. Otherwise, keep the same parameter name.
Examples of the differences can be found in a [previous …
=> Fixed a bug in normalizing URL parameters

camel/Extraction/ExtractedEndpointData.php, tests/Fixtures/TestPostBindedInterface.php, tests/Fixtures/TestPostBindedInterfaceController.php, tests/GenerateDocumentationTest.php
Hi,
The version `3.33.1` introduces a breaking change when you are using a type hinted argument that is an interface binded to a model via the service container.
Since an interface is not instantiable, you get this error when generating the documention:
```
Error 
Cannot instantiate interface App\Interfaces\YourModelInterface.php
at vendor/knuckleswtf/scribe/camel/Extraction/ExtractedEndpointData.php:262
258▕             // The argument does not have a type-hint
259▕             return false;
260▕         } else {
261▕             $argumentClassName = $argumentType->getName();
➜ 262▕             $argumentInstance = new $argumentClassName;
263▕             return ($argumentInstance instanceof Model);
264▕         }
265▕     }
266▕ }
+21 vendor frames 
22  artisan:37 …
```
=> Fix documentation generation when using binded interfaces instead of model classes as typed arguments

src/Extracting/Strategies/UrlParameters/GetFromLaravelAPI.php
Assuming that `Company` model exists with overridden `getRouteKeyName()` to return `slug`.
```
Route::get('company/{handle}', function($handle) {});
```
The inferred type for `handle` is `integer` instead of `string`.
Assuming that `AdminUser` model exists
```
Route::get('admin_users/{id}', function($id) {});
```
The inferred type for `id` is `string` instead of `integer`.
1. For type-hinted arguments that have a Model type, if `getRouteKeyName()` is the same as the primary key name (`getKeyName()`), use the type of the primary key (`getKeyType()`).
2. For parameters that do not satisfy the previous condition, try to guess their class, and then use `getKeyType()` immediately.
In step 2, after we guessed the class, we are immediately using `getKeyType()` which will return the primary key …
=> Fixed two bugs in inferring the URL parameter type

src/Extracting/ParsesValidationRules.php, tests/Fixtures/TestRequest.php, tests/Strategies/GetFromFormRequestTest.php
Issue requests #448  and #510 
This feature, allows to make 'No-example' values on FormRequest strategy.
It is possible to hide an attribute from example output.
**Only works on non required attributes**
Just add an example with a value 'No-example' on queryParameters or bodyParameters method on any FormRequest.
```php
namespace App\Http\Requests;
use Illuminate\Foundation\Http\FormRequest;
class PostRequest extends FormRequest {
public function rules(): array {
return [
'filter' => ['string', 'max:255'],
'page' => ['int'],
];
}
public function queryParameters() {
return [
'filter' => [
'description' => 'Name of post',
'example' => 'John',
],
'page' => [
'example' => 'No-example',
],
];
}
}
```
=> [Feature] No-example value with formRequest bodyParameter and queryPameters

src/Extracting/Strategies/ResponseFields/GetFromResponseFieldTag.php
I filled in the gap I left earlier in _ADD RESOURCES RESPONSE FIELD TAGS TO DOCUMENTATION (PR #505)._ The status code in definition of api resource / api resource collection won't cause failed generation anymore.
=> Fix response fields if response status code added to resource tag

src/Extracting/UrlParamsNormalizer.php
When documenting a laravel-json-api/laravel api I was getting a `Illuminate\Contracts\Container\BindingResolutionException` and the docs were failing to build. This PR catches those exceptions.
To give specifics: one of the arguments in the controller method is `LaravelJsonApi\Contracts\Routing\Route` (an interface). In the context of `knuckleswtf/scribe` that interface is not instantiating because `app()` doesn't have a binding to the interface.
=> Catch throwables when instantiating interface

src/Writing/PostmanCollectionWriter.php, tests/Fixtures/collection.json, tests/Unit/PostmanCollectionWriterTest.php
This update brings global bearer token setter in the postman file. If you set `use_value` as `{{token}}` in the scribe config file it'll automatically populate it when postman file is generated.
In you postman variables you can set that token automatically when sending login request using Postman's `Tests`. You can set this JS code in Tests tab and JWT token will be automatically populated and used globally by the API.
```javascript
var jsonData = JSON.parse(responseBody);
pm.environment.set("token", jsonData.login.access_token);
```
=> Adding support of global bearer token variable.

src/Extracting/Strategies/UrlParameters/GetFromLaravelAPI.php
Fix `Undefined offset: -1` error for when URL is like `{lang}/users`
=> Fixed a bug in laravel get name of url thing

resources/views/components/field-details.blade.php
I noticed that my boolean fields were documented with "Example: ``". So I investigated and found that it attempts to document `false`, but not `true`. And it didn't actually use the right variable.
=> Show boolean examples properly

src/Commands/GenerateDocumentation.php, src/Extracting/Strategies/ResponseFields/GetFromResponseFieldAttribute.php, src/Writing/OpenAPISpecWriter.php
This PR removes two redundant imports from `src/Commands/GenerateDocumentation.php` that were not used and one import of a non-existing class in `src/Writing/OpenAPISpecWriter.php`
=> Remove redundant imports

src/Commands/GenerateDocumentation.php, src/Scribe.php, src/Tools/Globals.php, tests/GenerateDocumentation/BehavioursTest.php
I think it'll be useful to have a `beforeGenerating` callback/hook. 
It can be used to replace a service container binding or fake certain events for example. 
I think it's a better option instead of listening to the default Laravel `CommandStarting` event and checking on the command type. Especially since the package already provides an `afterGenerating` callback.
=> Feature: Add bootstrap hook

src/Writing/OpenAPISpecWriter.php, tests/Unit/OpenAPISpecWriterTest.php
This PR adds a generation of property types for nested objects inside responses during openapi generation.  
Previously if the response contained nested objects, it was marked simply as `object`, and no additional params were generated. Now `OpenAPISpecWriter.php` will iterate through its properties and generate specs for them.
<details>
<summary><h3>Previously</h3></summary>
```YAML
'201':
description: ''
content:
application/json:
schema:
type: object
#example: ...
properties:
this:
type: string
example: shouldn't be ignored
and this:
type: string
example: too
description: Parameter description, ha!
sub level 0:
type: object
example:
sub level 1 key 1: sl0_sl1k1
sub level 1 key 2:
- sub level 2 key 1: sl0_sl1k2_sl2k1
sub level 2 key 2:
sub level 3 key 1: sl0_sl1k2_sl2k2_sl3k1
sub level …
```
=> Openapi nested objects properties

src/Writing/OpenAPISpecWriter.php
When generating the documentation, the OpenAPI does not include `properties` of objects that are nested in arrays. This PR aims at fixing this bug.
<details>
<summary><b>Before:</b></summary>
```yaml
openapi: 3.0.3
info:
title: 'Test'
version: 1.0.0
paths:
/api/test:
get:
responses:
'200':
description: Successful response
content:
application/json:
schema:
type: object
example:
someArray:
- anotherObjectKey: objectValue
properties:
someArray:
type: array
example:
anotherObjectKey: objectValue
items:
type: object
```
</details>
<details>
<summary><b>After:</b></summary>
```yaml
openapi: 3.0.3
info:
title: 'Test'
version: 1.0.0
paths:
/api/test:
get:
responses:
'200':
description: Successful response
content:
application/json:
schema:
type: object
example:
someArray:
- anotherObjectKey: …
```
=> OpenAPI: Set properties of objects nested in arrays

src/Attributes/Endpoint.php, tests/Strategies/Metadata/GetFromMetadataAttributesTest.php
I have changed the definition of the attributes for Endpoint so that they can be used as class attributes. 
This is useful if you use a library like [Laravel Actions] (https://github.com/lorisleiva/laravel-actions) where you have one controller per route.
=> Allow Endpoint-attribute to act as class target

phpunit.xml, src/Tools/WritingUtils.php, tests/Unit/WritingUtilsTest.php
This PR changes the way of generating examples for languages `PHP`, `JS`, and `Python`
Previously there was an issue when you had nested filters defined for your route like
```
[
'data' => 'filled|array',
'data.*' => 'required|array',
'data.*.is_file' => 'required|boolean',
]
```
Possible connected issue: https://github.com/knuckleswtf/scribe/issues/308 and https://github.com/knuckleswtf/scribe/issues/455
Now Scribe will nicely generate examples for them.
=> Fix nested filters when generating examples for PHP, JS and  Python

src/Tools/WritingUtils.php, tests/Unit/WritingUtilsTest.php
Fixed: When using nested arrays as query parameters, the bash examples throw an exception. 
Example: `filter[category][]=2&filter[category][ ]=6` broke the existing code. 
Solution: Check if the parameter is an array and handle it accordingly.
=> added support for nested arrays as query parameters for bash examples

src/Extracting/ParsesValidationRules.php, tests/Unit/ValidationRuleParsingTest.php
addMissingParentFields was checking for the existence of 'name.*' but then renaming to 'name' before saving.
Add a check to see if 'name' already exists to avoid overwriting a parent that is not missing.
fix #608
=> Required array overwritten

src/Extracting/ParsesValidationRules.php, tests/Strategies/GetFromFormRequestTest.php, tests/Unit/ValidationRuleParsingTest.php
Add a description to Closure rule with a DocComent:
```php
$request->validate([
'complex_rule' => [
/** This is a very specific validation therefore it needs a better description */
function ($attribute, $value, $fail) { $fail('error'); }
],
]);
```
Add more info to a Custom Validation Rule:
```php
class CustomRule implements Rule
{
// ...
public static function docs(): array
{
return [
'description' => 'This rule makes something very specific',
'example' => '52KB',
];
}
}
```
This is a followup for #551
I'm missing the tests and documentation changes, if you could point me where and how should I do them it'd be nice.
=> Documentation for custom rules and closure rules

composer.json
Fix Laravel 10 compatibility.
Since Laravel v10 uses "nunomaduro/collision" v7, Scribe needs to support it as well.
=> Fix Laravel 10 compatibility

src/Extracting/ParsesValidationRules.php, tests/Fixtures/TestIntegerBackedEnum.php, tests/Fixtures/TestStringBackedEnum.php, tests/Unit/ValidationRuleParsingTest.php
Adds description, example and type for Laravel's Enum Rule.
Fixes #579
=> Parse Enum Rule

src/Extracting/Extractor.php, tests/Unit/ExtractorPluginSystemTest.php
The `sortBy` function from Laravel does not modify the collection's sort order. It returns a new sorted collection.
=> Fix sorting of multiple responses by status code

src/Commands/GenerateDocumentation.php, tests/GenerateDocumentation/BehavioursTest.php
It will throw error if there is no config file in `config/scribe.php`.
We should check if this file exists or not, if it's not exists, just ignore upgrade config.
Before:
After:
=> Ignore upgrade check if user hasn't published config yet

src/Extracting/ApiDetails.php
Whenever new documentation is generated, it should ideally not change if none of the backing endpoints or configuration has changed. I think this randomisation should not occur while generating the contents of API documentation.
=> Remove unnecessary randomisation from auth description

src/Extracting/Strategies/UrlParameters/GetFromLaravelAPI.php
Due to legacy reasons, in my codebase I have all the models being in the root namespace, not in the `\App\Models` namespace.
When trying to run `php artisan scribe:generate`, it would immediately fail when trying to actually load my models (`Cannot declare class Account, because the name is already in use`, because of the autoloading of `class_exists`. Setting the autoload to false made everything work again.
For what it's worth, the parameter it's checking does use Model Binding, so it sounds like it shouldn't be doing this anyway? (`UrlParamsNormalizer::getTypeHintedEloquentModels` finds it)
But either way, thought I'd submit this fix!
=> Don't autoload with class_exists

src/Extracting/Strategies/GetFromFormRequestBase.php
rules() are now [optional as of Laravel 10.9](https://github.com/laravel/framework/releases/tag/v10.9.0)
=> `rules()` are optional for GetFromFormRequestBase

src/Extracting/ParsesValidationRules.php, tests/Unit/ValidationRuleParsingTest.php
Add a missing string concatenation when dealing with enum rules and a test for it.
closes #665
=> fix: enum rule no longer overrides description

src/Extracting/InstantiatesExampleModels.php, src/Extracting/Shared/ApiResourceResponseTools.php, src/Extracting/Strategies/Responses/UseApiResourceTags.php, tests/Fixtures/TestController.php, tests/Fixtures/TestEmptyApiResource.php, tests/GenerateDocumentation/BehavioursTest.php, tests/Strategies/Responses/UseApiResourceTagsTest.php
Update：
* Allow generate document without @apiResourceModel tag (but will remind you didn't use the @apiResourceModel tag)
This is a little feature to allow the document generate when the JsonResource is working with empty resource which means won't have any model to specify on the @apiResourceModel tag.
This might help some project using JsonResource to manage the api response which like webhook api or none data response api.
From [#652](https://github.com/knuckleswtf/scribe/issues/652).
=> Support `@apiResource` with missing `@apiResourceModel`

src/Writing/CustomTranslationsLoader.php
This PR addresses a compatibility issue with Statamic. The `CustomTranslationsLoader` class was previously using `FileLoader`, which led to conflicts as Statamic also mutates the loader. 
To resolve this, we've refactored `CustomTranslationsLoader` to use `LoaderContract` instead of `FileLoader`. This change enhances flexibility and ensures compatibility with Statamic and potentially other packages that mutate the loader.
Key Changes:
- `defaultLoader` property type is now `LoaderContract`.
- Constructor now accepts `LoaderContract` instead of `FileLoader`.
This change is crucial for ensuring our package's seamless integration with Statamic. Please review and provide feedback.
=> Refactor CustomTranslationsLoader for Compatibility with Statamic

src/Extracting/Strategies/PhpAttributeStrategy.php, tests/Strategies/Headers/GetFromHeaderAttributeTest.php
Our application has an extra header that needs to be sent with most (but not all) requests. It is not ideal to have to write `#[Header('Special-Header', 'this-needs-to-be-created-dynamically-at-runtime')]`
This PR makes it possible to extend the Header attribute.
=> Provide ability to extend Header attribute

resources/views/components/field-details.blade.php
Adds step="any" to input type when type is number to prevent a bug that occurs when number is used for non integer values.
Example:
Let's have an API that support Latitude and Longitude as input values
/*
* @queryParam lat number Latitudine. Example: 45.3267105
* @queryParam lng number Longitudine. Example: 7.995482
*/
The generated documentation example will have a field that look like this:
```html
<input type="number" style="display: block;" name="lat" data-endpoint="GETapi-v2-carrier-eolo-secondary-check" value="45.3267105" data-component="query">
```
As per validation rules the browser won't let you indroduce any value that isn't an integer number, so if you need to enter a precise value for testing it will be impossible.
Adding 'step="any"' makes possible to input any numeric value, …
=> Fix float values 

resources/views/partials/example-requests/bash.md.blade.php, resources/views/partials/example-requests/javascript.md.blade.php, resources/views/partials/example-requests/php.md.blade.php, resources/views/partials/example-requests/python.md.blade.php
Currently the Postman and OpenAPI writers both make allowances for when the `Content-Type` header has been set to `multipart/form-data` to render different output. This extends the same logic to the generated example code, which currently only uses the `multipart/form-data` format if there is a file required to send for the endpoint.
=> Ensure example code supports multipart/form-data without files

src/Writing/Writer.php
I had an issue with generating documentation on Laravel 10, please check 
https://github.com/knuckleswtf/scribe/issues/683
I solved it by using the public_path() method in the writer.php
=> Fix path traversal on Laravel 10

resources/js/tryitout.js
Hi,
This fix allow to put a dot character into the endpoint.
For my case, I have this error when I click on "Try it out" : 
https://stackoverflow.com/questions/17563296/does-queryselectorall-support-the-period-character-in-an-id
=> Allow dot char into endpoint

src/Writing/OpenAPISpecWriter.php
Objects with empty properties are being serialized as `[]` in the resulting `openapi.yaml`, which is invalid OpenAPI. This was already being handled in a couple places, just missed a few. I also replaced the `$EMPTY` class prop with a function that also performs the empty check. 
Luckily, `TheSideProjectAPI` actually has an example of this bug! I tested with that repo and the fix seemed to work. 
First time working in php, pointers welcome!
=> add empty check for properties

src/Writing/OpenAPISpecWriter.php
In addition to the existing 2 headers, the Authorization header is also not allowed. Instead it is taken care of by the security schemes
=> Exclude Authorization header from openapi specs.

src/Tools/WritingUtils.php, tests/Unit/WritingUtilsTest.php
Hi,
Fix sample body with an object of array. For example :
```php
#[BodyParam('fields', 'object[]', 'Form\'s fields', required: false)]
#[BodyParam('fields[].name', 'string', 'Field\'s name', required: true, example: 'experience')]
#[BodyParam('fields[].label', 'string', 'Field\'s label', required: true, example: 'Expérience')]
#[BodyParam('fields[].type', 'string', 'Field\'s type', required: true, example: 'textarea')]
#[BodyParam('fields[].order', 'number', 'Field\'s order', required: true, example: 1)]
```
Before
```json
{
"name": "Experience Form",
"fields": {
"name": "experience",
"label": "Exp\u00e9rience",
"type": "textarea",
"order": 1
}
}
```
After
```json
{
"name": "Experience Form",
"fields": [
{
"name": "experience",
"label": "Exp\u00e9rience",
"type": "textarea",
"order": 1
} …
```
=> Fix sample body with array of object

config/scribe.php, resources/views/partials/example-requests/bash.md.blade.php, resources/views/partials/example-requests/javascript.md.blade.php, resources/views/partials/example-requests/php.md.blade.php, resources/views/partials/example-requests/python.md.blade.php
- makes the workaround in #721 work
- still needs tests (linking #717)
=> Support dynamic base URL

camel/Camel.php, config/scribe.php, tests/GenerateDocumentation/OutputTest.php
…to determine where in the ordering all unspecified groups will be placed.
Opening this one as a Draft so we can talk about implementation/config @shalvah. Hopefully this is a feaure Scribe can support. 
This PR is adding a feature which allows you to bury endpoints at the bottom of the list for example older versions that you don't want consumers going to first. 
This is done with the following config:
```php
return [
// ...top of config
'order' => [
'First Group',
'Second Group',
'*',
'Last Group',
],
// ...rest of config
];
```
This will generate the groups like the screenshot below:
=> `groups.order` now supports `*` wildcard, so you can put groups at the end

resources/views/components/nested-fields.blade.php
If the request rule for an enum was inside a nested object field, it wouldn't display the values, as the template was using the wrong variable ($field instead of $subfield like it does for the rest of the component params)
=> Fixed enum values not displaying in nested objects

src/Extracting/InstantiatesExampleModels.php
When creating a model from a factory, the initial result does not contain any values generated by the database. The `refresh` pulls the actual values from the database, thus including the values generated by the database.
=> Include database-generated values on factory create

src/Extracting/ParsesValidationRules.php, tests/Unit/ValidationRuleParsingTest.php
If there are nested fields in the request validation rules, the parsing is incorrect.
This PR fixes this, so that it also works when an array is expected, see examples below.
Before the change
After the change
```php
class ExampleRequest extends FormRequest
{
public function rules()
{
return [
'*.foo' => 'required|array',
'*.foo.*' => 'required|array',
'*.foo.*.bar' => 'required',
];
}
public function bodyParameters()
{
return [
'*.foo' => [
'description' => 'This is not shown (intended?).',
],
'*.foo.*' => [
'description' => 'A nested field.',
],
'*.foo.*.bar' => [
'description' => 'A double-nested field.',
],
];
}
}
```
**Note:** The first description (of `*.foo` is ignored and will not be shown by scribe. I'm not sure if this is intended?
Single object example
```json
[
{
"foo": [
{ …
```
=> Fixed parsing of nested fields in validation rules

camel/Extraction/Parameter.php, src/Extracting/Extractor.php, src/Extracting/ParamHelpers.php, src/Extracting/ParsesValidationRules.php, src/Extracting/Strategies/BodyParameters/GetFromBodyParamTag.php, src/Extracting/Strategies/GetFieldsFromTagStrategy.php, src/Extracting/Strategies/QueryParameters/GetFromQueryParamTag.php, src/Extracting/Strategies/UrlParameters/GetFromUrlParamTag.php, tests/GenerateDocumentation/OutputTest.php, tests/Strategies/BodyParameters/GetFromBodyParamTagTest.php
Allow null parameter in the generation of API example specification
```
@bodyParam col_id integer required ID Example: null 
@bodyParam col_name string name Example: null
```
Example of use 
We want to put null value in the database.
We want to pass null as ID to create a new ID. //presence of parameter required
We want to pass null instead of '' string.
=> Support specifying `Example: null` in annotations

composer.json
✅  This just allows to install `nunomaduro/collision: v8` 
⚠️ If someone want's to use **v8** - then **PHP 8.2** is minimum required.
=> Allow collision v8

camel/Camel.php, phpunit.xml, src/Commands/GenerateDocumentation.php, src/Commands/Upgrade.php, src/Configuration/PathConfig.php, src/Extracting/ApiDetails.php, src/GroupedEndpoints/GroupedEndpointsFactory.php, src/GroupedEndpoints/GroupedEndpointsFromApp.php, src/GroupedEndpoints/GroupedEndpointsFromCamelDir.php, src/Writing/Writer.php, tests/GenerateDocumentation/OutputTest.php, tests/Unit/PathConfigurationTest.php
- **Added** the ability to configure the `scribe.php` (or custom php config file) independently of the temp directory.
=> Allow config and temp directories to be configured independently.

config/scribe.php, resources/views/external/elements.blade.php, resources/views/external/rapidoc.blade.php, resources/views/external/scalar.blade.php, src/Tools/ConfigDiffer.php, src/Writing/ExternalHtmlWriter.php
- [Stoplight Elements](https://github.com/stoplightio/elements) as an external UI
- Support `try_it_out` and `logo` config options in rapi-doc external UI
- Allow passing of custom HTML attributes to external UIs
- Fix `config:diff` command for tuple configs
=> External UI improvements

README.md
Update README:
- Update URL for migration guide v3 and v4
- Remove errant backtick
=> Update/fix migration URL in README. Remove errant backtick

resources/views/themes/elements/endpoint.blade.php
Adds  `sl-overflow-y-auto` in example request so that content is not truncated but can scroll.
Fixes #810 
Before
After
=> Fixes #810

src/Writing/OpenAPISpecWriter.php
The enum values for an array query parameter are correctly identified in the Scribe documentation, but are not shown in the generated OpenAPI document. 
This PR adds to the enum values for the array query parameter in the OpenAPI document.
<details><summary>Before / After OpenAPI document</summary>
**Before**
```yaml
parameters:
-
in: query
name: type
description: 'Filtre sur le type'
example:
- fichier
required: false
schema:
type: array
description: 'Filtre sur le type'
example:
- fichier
items:
type: string
``` 
**After**
```yaml
parameters:
-
in: query
name: type
description: 'Filtre sur le type'
example:
- fichier
required: false
schema:
type: array
description: 'Filtre sur le type'
example:
- fichier
items:
type: string
enum:
- app
- app_inst
- bdd
- fichier
- rpa
- monarch
``` …
=> fix: include enum options for array values in OpenAPI spec

resources/views/external/elements.blade.php
[examples example](https://github.com/stoplightio/elements/blob/main/examples/static-html/zoom-api/index.html)
Based on the code examples from the official repository of 'stoplightio/elements', it appears that our generation template is missing the setting of the 'body' 'height' to '100vh', which causes a styling error in the sidebar. The sidebar height cannot be fixed and changes with the height of the content page on the right. The page is as follows:
After the fix:
=> Fix Sidebar Style Error for 'External_Static' Type and 'Elements' Theme

camel/Extraction/ResponseField.php
Allowing examples to be shown in the templates in the response description set
=> Allow examples to be shown in response fields

resources/js/tryitout.js
=> added cast number value to float if value is string

src/Tools/Utils.php, src/Writing/Writer.php, tests/Unit/UtilsTest.php
Fixes https://github.com/knuckleswtf/scribe/issues/793 
Referring to other creation methods, it was found that a method should be encapsulated for calling.
Additionally, remove the Str class that is not referenced in the Write class.
=> make directory recursive

src/Extracting/ParsesValidationRules.php, tests/Unit/ValidationRuleParsingTest.php
Fixes #824 
Adds support for translating rules like `'validation.max.string'` for translation engines that don't support returning an array for `'validation.max'`.
=> Fix translating rules with translation engines that don't return arrays.

src/Extracting/ParsesValidationRules.php
When using it in the form request:
It generates the examples, but it doesn't generate the fields in the body parameters.
If I remove the parent index:
It generates the fields in the body parameters, but it doesn't generate the examples.
After the correction, passing the parent index, it generates the examples and also generates the fields in the body parameters.
=> Array with Form request doesn't generate both example and fields at the same time

resources/views/external/elements.blade.php
Two fixes when choose theme="elements" :
- use the title in config
- don't set logo param if not set
=> External Elements : fix title & missing logo

src/Extracting/Strategies/Responses/ResponseCalls.php, src/Scribe.php, src/Tools/Globals.php
Add the hook **afterResponseCall** allowing to modify the result after the API call (for example to reduce large examples with hundred of lines to 5 maximum, to remove a sensible data, ...).
The doc update is available here : https://github.com/knuckleswtf/scribe-docs/pull/29
=> feat: add afterResponseCall hook

src/Writing/OpenAPISpecWriter.php, tests/Unit/OpenAPISpecWriterTest.php
This PR brings the generator in line with the OpenAPI 3.0 Spec (according to https://swagger.io/docs/specification/describing-responses/) and implements multiple response content types and support for multiple response schemas in a single content type (via oneOf).
Currently missing a Unit test for this behavior (will add this soon).
I couldn't find this specific info anywhere in the documentation so I think there is no change necessary.
As I'm not familiar with Postman I don't know if any change is necessary there.
=> Allow multiple content types and schemas (via oneOf) according to OpenAPI 3.0 spec

src/Writing/OpenAPISpecWriter.php, tests/Unit/OpenAPISpecWriterTest.php
Fixed the oneOf problem when using more than two responses with the same status code. Solving the problem related to this issue: https://github.com/knuckleswtf/scribe/issues/862
=> fix: multiple responses with the same status code

resources/views/themes/elements/index.blade.php
When uploading a file the Content-Type header must not be set otherwise the browser cannot set the right boundaries for the multipart formdata payload.
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest_API/Using_FormData_Objects
TryItOut editor in `elements` theme is currently setting the Content-Type header and therefore file uploads do not work.
Should resolve https://github.com/knuckleswtf/scribe/issues/764
=> fix: fixes elements theme mutlipart form file upload

src/Writing/HtmlWriter.php
When you set type to `external_static` and set custom static output_path, it still points to default path in generated HTML.
Generated part of scalar HTML (before PR, output_path is different from `public/docs`):
```html
<script
id="api-reference"
data-url="../docs/openapi.yaml">
</script>
```
=> Allow custom output path for `static` and `external_static` instead of only `static`

src/Extracting/Strategies/GetFromInlineValidatorBase.php
=> Fix #879 (Comments are ignored for validator parameters with non string/array (e.g. conditional) rule lists)

resources/css/theme-default.style.css
Fix issue #867 and remove some duplicated code on `resources/css/theme-default.style.css`
=> Fix issue 857 (Response fields overflows to the dark box zone)

resources/views/themes/elements/components/field-details.blade.php
This **PR** fix the rendering of boolean examples with the **elements theme**. Currently, there's an issue and boolean example cases like `false` and `true` aren't rendering in the right way. At next you can see an image showing this issue:
In this image you can see that a `false` example value is not rendered and `true` is rendered like `1`.
In this image you can see that boolean example cases are now rendering nicely.
=> Fix display of boolean examples on the elements theme

resources/views/themes/elements/index.blade.php
Replaces html special characters with html entities in response.
If an API response contains html this is currently not visible in Received Response section.
Before
After
=> Fixes html content not showing in received response

src/Writing/PostmanCollectionWriter.php
The generated postman collection from my project was not valid. It contained several `value` entries for query parameters that were pure integer values. This is not compatible with the postman format, which requires strings.
Therefore, I added `urlencode` to the `value` in `PostmanCollectionWriter` to avoid validation errors.
=> Postman collection export: encoding value to prevent validation errors

resources/css/theme-default.style.css, resources/js/tryitout.js
This PR addresses an issue where the output of Laravel's dd() function is rendered as plain text in the generated documentation by Scribe. The changes introduce a selective rendering mechanism that safely treats dd() output as HTML while keeping all other API responses as plain text, ensuring proper security.
- Laravel dd() detection: The script now checks for the presence of sf-dump in the response to identify dd() output.
- Secure rendering: Only the detected dd() output is rendered using innerHTML to display the HTML dump correctly. Other responses continue to use textContent to avoid XSS vulnerabilities.
This update improves the developer experience by ensuring that Laravel debug outputs are correctly formatted in the API documentation, while maintaining security.
=> Improve Laravel dd() Output Rendering in Scribe Documentation

src/Extracting/ParsesValidationRules.php, tests/Unit/ValidationRuleParsingTest.php
Adds support for parsing the `exists` validation rule in the `parseRule` method of the `ParsesValidationRules` trait. 
This will ensure that the generated documentation accurately reflects the use of the `exists` rule, preventing incomplete or misleading validation descriptions.
Fixes #882
=> feat: Add parsing support for exists rule in parseRule switch case

src/Writing/OpenAPISpecWriter.php
When outputting to a swagger file, add a `description` field to the field whose type is object.
=> feat: Add description to type as object when generating swagger file

src/Extracting/Shared/ValidationRulesFinders/RequestValidateFacade.php, src/Extracting/Strategies/GetFromInlineValidatorBase.php, tests/Fixtures/TestController.php, tests/Strategies/GetFromInlineValidatorTest.php
I have a project that use Facades to validate, then i think that this is useful.
Docs update:
- https://github.com/knuckleswtf/scribe-docs/pull/31
=> Allow parse expressions with Request::validate facade usage

src/Attributes/Response.php, tests/Strategies/Responses/UseResponseAttributesTest.php
Hello 👋 
Thank you for the package, we are really enjoying all the work you put into it. I hope you will accept this small change which we think might be a bug :) 
When having a response with no content in it, it ends up showing as plaintext in openapi spec.
```php
#[Response(status: 404, description: 'Organization not found')]
```
Will be generated as 
```yaml
404:
description: 'Organization not found'
content:
text/plain:
schema:
type: string
example: 'null'
```
To fix this problem, we make sure that if the content is null, we pass `null` forward when converting the attribute to an array. Previously the `null` value was passed through `json_encode` which will convert it into `'null'`. 
After this solution, we end up with 
```yaml
404:
description: 'Organization not found'
content: …
```
=> Fix parsing no content into null instead of 'null'

src/Writing/Writer.php
Added another str_replace so that the case for external_laravel with the theme "elements" is also matched.
Without the new str_replace the following is generated in the index.blade.php file:
`<elements-api apiDescriptionUrl="../docs/openapi.yaml" ...`
With the new str_replace the relative url is replaced with a route:
`<elements-api apiDescriptionUrl="{{ route("scribe.openapi") }}" ...`
The problem only occurs if laravel.docs_url is changed manually.
Then the openapi.yaml-file cannot be found.
This is not a problem with scalar and rapidoc, as the attribute (e.g. data-url) matches a lowercase ‘url’ correctly.
=> add str replace for external_laravel with theme "elements"

src/Extracting/Shared/ValidationRulesFinders/RequestValidateFacade.php
This PR fixes a bug when RequestValidateFacade is parsing controller methods in specific context.
Given this exemple :
```php
#[Group('ExampleGroup')]
#[ResponseFromApiResource(ExampleResource::class, ExampleModel::class, collection: true, paginate: 20)]
public function handle(Request $req, EnumType $type, int $val): ResourceCollection
{
$modelType = match ($type) {
EnumType::OPTION_A => ModelA::class,
};
// Ensure presence in DB or fail to 404
$model = $modelType::findOrFail($val);
return ExampleResource::collection($model);
}
```
When generating doc with artisan `RequestValidateFacade` will end in the exception 
```
Object of class PhpParser\Node\Expr\Variable could not be converted to string
at vendor/knuckleswtf/scribe/src/Extracting/Shared/ValidationRulesFinders/RequestValidateFacade. …
```
=> fix: RequestValidateFacade Variable could not be converted to string

src/Writing/PostmanCollectionWriter.php
The Postman API accepts the types 'text' and 'file', so passing 'text' with an integer value throws the error from the issue. To fix this the value is always cast to string. The string value is ok for the api and the generated documentation works
=> fix: Collection with formdata malformed for API
